import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./Providers";
import NavLeft from "./Components/navleft";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-100 flex flex-row relative`}>
        <div className="w-[10rem] flex  flex-col  justify-center  items-center fixed left-0 h-[100vh] text-xl ">
          <NavLeft />
        </div>
        <main className="w-full z-[9999px] ">
          <Providers>{children}</Providers>
        </main>
        <ul className="w-[10rem] fixed right-0 h-[100vh] flex flex-col  justify-center  items-start text-left space-y-6">
          <li data-to-scrollspy-id={"Profile"} className="rounded-md">
            <a href="#Profile">Profile</a>
          </li>
          <li data-to-scrollspy-id={"Language"} className="rounded-md">
            <a href="#Language">Language</a>
          </li>
          <li data-to-scrollspy-id={"Project"} className="rounded-md">
            <a href="#Project">Project</a>
          </li>
          <li data-to-scrollspy-id={"Contact"} className="rounded-md">
            <a href="#Contact">Contact</a>
          </li>
        </ul>
      </body>
    </html>
  );
}
